name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        kubernetes: [1.32.9, 1.33.5, 1.34.1]
        laravel: [11, 12]
        prefer: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - K8s v${{ matrix.kubernetes }} --${{ matrix.prefer }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, yaml
          coverage: pcov

      - uses: actions/cache@v4
        name: Cache dependencies
        with:
          path: ~/.composer/cache/files
          key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.prefer }}-${{ hashFiles('composer.json') }}

      - uses: medyagh/setup-minikube@latest
        name: Setup Minikube
        with:
          minikube-version: 1.37.0
          container-runtime: containerd
          kubernetes-version: v${{ matrix.kubernetes }}

      - name: Run Kubernetes Proxy
        run: |
          kubectl proxy --port=8080 --reject-paths="^/non-existent-path" &

      - name: Install dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}.0" --dev "orchestra/testbench" --no-interaction --${{ matrix.prefer }} --prefer-dist

      - name: Setup in-cluster config
        env:
          TEST_TOKEN: some-token
          TEST_CERT: c29tZS1jZXJ0Cg==
          TEST_NAMESPACE: some-namespace
        run: |
          sudo mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
          echo "$TEST_TOKEN" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/token
          echo "$TEST_CERT" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          echo "$TEST_NAMESPACE" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/namespace
          sudo chmod 644 /var/run/secrets/kubernetes.io/serviceaccount/token
          sudo chmod 644 /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          sudo chmod 644 /var/run/secrets/kubernetes.io/serviceaccount/namespace

      - name: Setting CRDs for testing
        run: |
          kubectl apply -f https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/main/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml

      - name: Run tests
        run: |
          vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
